import Head from "next/head";
import HeroSection from "@/components/Home/HeroSection";
import { Fragment, useEffect, useState } from "react";
import FeaturedPosts from "@/components/Post/FeaturedPosts";
import { getFeaturedPosts } from "@/lib/posts-util";

export default function Home(props) {
 const {posts} = props

  return (
    <Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeroSection />
      <FeaturedPosts posts={posts} />
    </Fragment>
  );
}


export function getStaticProps() {

   const posts = getFeaturedPosts()
   
   return {
    props : {
      posts :posts
    }
   }
}